version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9201:9200"
    depends_on:
      - db
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/b2w
    ports:
      - "3001:3000"
    depends_on:
      - db
  